#!/bin/bash
(
 ./buildroot-2021.02/output/host/bin/qemu-system-aarch64 -M virt \
 -m 1024M \
 -cpu cortex-a53 -nographic -smp 1 \
 -kernel ../openwrt-19.07.7-armvirt-64-Image \
 -append "rootwait root=/dev/vda console=ttyAMA0" \
 -netdev user,id=eth0,hostfwd=tcp::8888-:80,hostfwd=tcp::2222-:22 \
 -device virtio-net-device,netdev=eth0 \
 -drive file=../root.ext4,if=none,format=raw,id=hd0 \
 -device virtio-blk-device,drive=hd0 \
 -device virtio-rng \
 -soundhw hda -audiodev id=pa,driver=pa
)

